[build]
  # Ajusta esto si tu build genera el index.html en otra carpeta,
  # p. ej. "build" o "dist". Si realmente tu index.html está en la raíz,
  # deja publish = ".".
  publish = "."

  # Si tienes un comando de build, especifícalo:
  command = "npm run build"

[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
